<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    const ROLE_ADMIN = 'ADMIN';
    const ROLE_CONTENT_USER = 'CONTENT_USER';
    const ROLE_USER = 'USER';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    /**
     * Check if the user is an admin
     */
    public function isAdmin(): bool
    {
        return $this->role === self::ROLE_ADMIN;
    }

    /**
     * Check if the user is a content user
     */
    public function isContentUser(): bool
    {
        return $this->role === self::ROLE_CONTENT_USER;
    }

    /**
     * Check if the user is a regular user
     */
    public function isUser(): bool
    {
        return $this->role === self::ROLE_USER;
    }

    /**
     * Get all courses created by the user
     */
    public function courses(): HasMany
    {
        return $this->hasMany(Course::class, 'creator_id');
    }

    /**
     * Get all exercise submissions made by the user
     */
    public function exerciseSubmissions(): HasMany
    {
        return $this->hasMany(ExerciseSubmission::class);
    }

    /**
     * Get all chat groups that the user belongs to
     */
    public function chatGroups(): BelongsToMany
    {
        return $this->belongsToMany(ChatGroup::class, 'chat_group_members', 'user_id', 'chat_group_id')
            ->withPivot('joined_at')
            ->withTimestamps();
    }

    /**
     * Get the user's approval request
     */
    public function approval(): HasMany
    {
        return $this->hasMany(UserApproval::class);
    }
    
    /**
     * Get all exercise answers submitted by the user
     */
    public function exerciseAnswers(): HasMany
    {
        return $this->hasMany(UserExerciseAnswer::class);
    }

    /**
     * Get courses managed by this user (if content user)
     */
    public function managedCourses()
    {
        return $this->hasMany(Course::class, 'content_user_id');
    }
    
    /**
     * Get courses registered by this user
     */
    public function registeredCourses()
    {
        return $this->belongsToMany(Course::class, 'course_registrations')
            ->withPivot('registered_at')
            ->withTimestamps();
    }
    
    /**
     * Get chat groups created by this user
     */
    public function createdChatGroups()
    {
        return $this->hasMany(ChatGroup::class, 'created_by');
    }
    
    /**
     * Get messages sent by this user
     */
    public function messages(): HasMany
    {
        return $this->hasMany(Message::class, 'sender_id');
    }
    
    /**
     * Get user approval records for this user (if regular user)
     */
    public function approvalRecords()
    {
        return $this->hasMany(UserApproval::class, 'user_id');
    }
    
    /**
     * Get user approval records made by this user (if content user)
     */
    public function approvedUsers()
    {
        return $this->hasMany(UserApproval::class, 'content_user_id');
    }
    
    /**
     * Get admin reports generated by this user (if admin)
     */
    public function generatedReports()
    {
        return $this->hasMany(AdminReport::class, 'generated_by_admin_id');
    }

    /**
     * Get the user approval record for this user
     */
    public function userApproval(): HasOne
    {
        return $this->hasOne(UserApproval::class);
    }
    
    /**
     * Get the user approvals reviewed by this content user
     */
    public function reviewedApprovals(): HasMany
    {
        return $this->hasMany(UserApproval::class, 'content_user_id');
    }
    
    /**
     * Check if the user needs approval
     */
    public function needsApproval(): bool
    {
        return $this->hasRole('user') && (!$this->userApproval || $this->userApproval->isPending());
    }
}
